version: '3.9'

services:
# mongo
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    # volumes:
    #   - mongo_db:/data/db
    ports:
      - "2717:27017"
# express
  express-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://mongo_db:27017/Code_Samurai
      DB_NAME: my_db
      NAME: MMMim
    depends_on:
      - mongo_db

# volumes:
#   mongo_db: {}
